# events/events.py
#Design rule (memorize this):

#Events carry information. 
# They do NOT execute logic.
from dataclasses import dataclass
from datetime import datetime


class Event:
    """
    Base class for all events.
    """
    pass


@dataclass
class MarketEvent(Event):
    """
    Handles the event of receiving new market data.
    """
    symbol: str
    time: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float


@dataclass
class SignalEvent(Event):
    """
    Generated by a strategy.
    """
    symbol: str
    time: datetime
    signal_type: str   # 'LONG', 'SHORT', 'EXIT'
    strength: float = 1.0


@dataclass
class OrderEvent(Event):
    """
    Generated by the portfolio.
    """
    symbol: str
    order_type: str    # 'MKT'
    quantity: int
    direction: str     # 'BUY' or 'SELL'


@dataclass
class FillEvent(Event):
    """
    Generated by the execution handler.
    """
    time: datetime
    symbol: str
    quantity: int
    direction: str
    fill_price: float
    commission: float = 0.0
